spring.datasource.url=jdbc:mysql://localhost:3306/pickmenow-db?createTableIfNotExsist=true
spring.datasource.username=root
spring.datasource.password=enter your pass
spring.jpa.hibernate.ddl-auto=update




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=enter your mail
spring.mail.password= enter your pass
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

